# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy AlphaVictor Staging

on:
  push:
    branches:
      - staging

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    env:
      VUE_APP_API_ADMIN_URL: https://alphavictor-dev.azurewebsites.net/api/admin
      VUE_APP_API_PUBLIC_URL: https://alphavictor-dev.azurewebsites.net/api
      VUE_APP_BASE_URL: https://av.mythdigital.dev
      VUE_APP_AUTH_TENANT_NAME: alphavictordev
      VUE_APP_AUTH_EMAIL_LINK_SIGNIN_POLICY_NAME: B2C_1A_AVMAGICLINK
      VUE_APP_AUTH_SIGNIN_POLICY_NAME: B2C_1_SignUpSignIn
      VUE_APP_AUTH_CLIENT_ID: 6c690f94-d958-42eb-9ac8-f4b450337714
      VUE_APP_MIXPANEL_TOKEN: 7b6bcf728f7d60bf67b60554c2511329

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2

      - name: Node Package Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload SPA artifact
        uses: actions/upload-artifact@v2
        with:
          name: spa
          path: dist/apps/alphavictor-staging-web

  deploy_spa:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'dev'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: spa

      - name: Azure Static Web Apps Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # Action to perform
          action: upload
          app_location: .
          output_location: ''
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_DEPLOY_TOKEN }}
          skip_app_build: true